services:
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=test
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 4999:3306
  
  marker:
    container_name: marker
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mariadb://db:3306/
      - DB_DATABASE=test
      - DB_NAME=root
      - DB_PASSWORD=1234